### ISSUE TITLE
Could not find plugin "proposal-numeric-separator"

### ISSUE THREAD

**Issue by Lukavyi** [esetnik/customize-cra-react-refresh#10]
Error: [BABEL] /Users/taraslukavyi/Projects/traverz/traverz-admin/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/BabelDetectComponent.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/taraslukavyi/Projects/traverz/traverz-admin/node_modules/babel-preset-react-app/dependencies.js$0")

Can be reproduced if completely removed node_modules and package-lock and npm i

**Comment by esetnik** [comment]
@Lukavyi please reopen this issue against https://github.com/pmmmwh/react-refresh-webpack-plugin. I just integrate that plugin into create-react-app so there’s little I can do to help.
