### ISSUE TITLE
support question: how do i further customize module.exports after executing override(addReactFastRefresh())

### ISSUE THREAD

**Issue by laurencefass** [esetnik/customize-cra-react-refresh#15]
how do i further customize module.exports after executing 

```
module.exports = override(addReactRefresh())
```

e.g. how do i further assign config to module.exports without overriding the override? Can I add it to the object?

```
module.exports = {
  // Webpack config to use when compiling your react app for development or production.
  webpack: function(config, env) {
    // change configuration, e.g. config.output.publicPath = "/app1/"
    console.log("webpack config", config);
    return config;
  },
  //webpack dev server configuration when running the development server with 'yarn start'.
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      const config = configFunction(proxy, allowedHost);
      // change configuration e.g. config.sockPath = "/app1/sockjs-node"
      console.log("devServer config", config);
      return config;
    };
  },
}
}
```
thanks

**Comment by esetnik** [comment]
Hi @laurencefass. This is not a general support forum for using `customize-cra` and is only supposed to be used specifically for questions related to using the `customize-cra-react-refresh` plugin. So I think it's better to ask your question at [customize-cra](https://github.com/arackaf/customize-cra). In general if you want to further customize webpack you'd use the available functions, following [this example](https://github.com/arackaf/customize-cra#with-webpack) from the customize-cra documentation.
