### ISSUE TITLE
A simple test program rendering random  numbers is updating parent and sibling components when i update a single component in source code.

### ISSUE THREAD

**Issue by laurencefass** [esetnik/customize-cra-react-refresh#16]
I'm trying this for the first time with a very simple create-react-app consisting of a small collection of components outputting a random number to test for re-render. i was expecting installation of this package according to instructions to result in isolated updates to components but instead all siblings are re-rendered, as reflected by recalculation of random numbers. In summary: this package doesn't appear to have changed the default HMR.

Is my expectation correct or should all the components in a hierarchy re-render if i make a change to a leaf of that hierarchy?

code for testing:

```
import React from 'react';
import logo from './logo.svg';
import './App.css';

function Component1() {
  return (<>
    <h2>Component1</h2>
    <p>component key: {Math.random()}</p>
  </>) 
}

function Component2() {
  return (<>
    <h2>Component2</h2>
    <p>component key: {Math.random()}</p>
  </>);
}

function Component3() {
  return (<>
    <h2>Component3!</h2>
    <p>component key: {Math.random()}</p>
  </>);
}

function App() {
  return (
    <div className="App">
        <Component1></Component1>
        <Component2></Component2>
        <Component3></Component3>
    </div>
  );
}

```

thanks

**Comment by laurencefass** [comment]
ok i see... it preserves state. very cool.

**Comment by esetnik** [comment]
Glad you got it figured out. As you discovered, state is preserved, but it will not prevent rerenders of sibling components.
