### ISSUE TITLE
Failed to compile CRA v4

### ISSUE THREAD

**Issue by mihanizm56** [esetnik/customize-cra-react-refresh#18]
Hi, I recently have installed your lib and looks like it doesn't support the new CRA version, isn't it ?

  "customize-cra": "1.0.0",
  "customize-cra-react-refresh": "1.1.0",
  "react": "17.0.2",
  "react-dom": "17.0.2",
  "react-app-rewired": "2.1.8",
  "react-scripts": "4.0.3",
  "typescript": "4.1.5"
  
  
![image](https://user-images.githubusercontent.com/37120827/114285557-cfdf7c00-9a60-11eb-9c7a-a6b75b2a4e1f.png)

**Comment by esetnik** [comment]
@mihanizm56 in CRA v4 you do not need this library because react-refresh support is already included. See https://github.com/facebook/create-react-app/pull/8582 and [the v4 changelog](https://github.com/facebook/create-react-app/releases/tag/v4.0.0)

**Comment by mihanizm56** [comment]
Looks like a bug in cra https://github.com/facebook/create-react-app/issues/9904#issuecomment-817211684

**Comment by esetnik** [comment]
Yes, it may be a bug due to your specific configuration or project. I have had no issues with fast refresh in CRA v4 in my own projects.

**Comment by mihanizm56** [comment]
> Yes, it may be a bug due to your specific configuration or project. I have had no issues with fast refresh in CRA v4 in my own projects.

What is do you use?
In my projects there is no specific configuration, only aliases with rewired - if I disable rewired refresh, this doesn't refresh changes at all

**Comment by esetnik** [comment]
That's strange. Can you try creating a new CRA v4 app and make sure that fast refresh is working on your system? I am not a CRA maintainer and as such can't help too much with specific issues there. I suggest that you open an issue with them if it's not working for you.
