### ISSUE TITLE
Requires disableRefreshCheck: true

### ISSUE THREAD

**Issue by esetnik** [esetnik/customize-cra-react-refresh#3]
Waiting on a fix for https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/15

**Comment by EdvardasDlugauskas** [comment]
Looks like it was fixed. Can we expect a new release soon?

**Comment by esetnik** [comment]
@EdvardasDlugauskas when a new version of https://github.com/pmmmwh/react-refresh-webpack-plugin/ is released I will release a new version of this package. So far that has not happened.

**Comment by EdvardasDlugauskas** [comment]
@esetnik This package is using v0.1.3 of react-refresh-webpack-plugin, but the latest version seems to be v0.2.0 https://github.com/pmmmwh/react-refresh-webpack-plugin/releases, or am I missing something?

**Comment by esetnik** [comment]
The fix for #3 isn't included in v0.2.0. https://github.com/pmmmwh/react-refresh-webpack-plugin/compare/v0.2.0...master
