### ISSUE TITLE
Unable to install with npm registry error

### ISSUE THREAD

**Issue by garrettmaring** [esetnik/customize-cra-react-refresh#4]
I am seeing the error `error Couldn't find package "@pmmmwh/react-refresh-webpack-plugin" on the "npm" registry.`

**Comment by esetnik** [comment]
That's strange. I can see it on the registry at https://www.npmjs.com/package/@pmmmwh/react-refresh-webpack-plugin. Can you confirm which registry you're using?

**Comment by geraldarthurdavis** [comment]
This was on me! Sorry about that.
