### ISSUE TITLE
How can I test that it's working?

### ISSUE THREAD

**Issue by tmaiaroto** [esetnik/customize-cra-react-refresh#6]
It's still pretty slow to reload for me. Is there a way to see if it's working? If it's faster, it's only barely faster.

Any other tuning adjustments that could be made to pre-build or otherwise speed things up?

**Comment by esetnik** [comment]
One easy way to test if it’s working if your component updates after code changes without a full page reload.

With regard to performance tuning are you running your project inside a docker container on macOS? That could be one reason for performance issues as the hyperkit filesystem is very slow.

**Comment by tmaiaroto** [comment]
Actually, I have seen the component update without a full page reload. Interesting.

I am using it on an Arch Linux workstation.

Thanks! It must be better, but wish it was even faster.

**Comment by esetnik** [comment]
Are you using typescript?
