### ISSUE TITLE
Styled-components refresh entire page

### ISSUE THREAD

**Issue by mnemanja** [esetnik/customize-cra-react-refresh#7]
Hi there,
I've implemented fast-refresh in my CRA following the documentation.
It works when I make a change in a React component, but when I change the styled-component's style it does a whole page refresh. 

e.g.
![image](https://user-images.githubusercontent.com/1423218/76408712-a94a9f80-638d-11ea-9db7-93e795e5cffd.png)

**Comment by esetnik** [comment]
@mnemanja I think this should be reported to [pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) as it sounds like a bug in the underlying `react-refresh` webpack implementation and not related to `customize-cra-react-refresh`.

**Comment by mnemanja** [comment]
Seems this was some sort of bug that was self resolved since then.
