### ISSUE TITLE
Documentation: should @pmmmwh/react-refresh-webpack-plugin be used?

### ISSUE THREAD

**Issue by mnemanja** [esetnik/customize-cra-react-refresh#8]
The documentation here mentions customize-cra and how to implement it, but it also mentions @pmmmwh/react-refresh-webpack-plugin without any guides.

Can you please update the documentation so that it either includes it in the implementation or remove it altogether if it is not needed?

**Comment by esetnik** [comment]
Hi @mnemanja i'm not sure I fully understand the question. The whole purpose of this plugin is to inject `@pmmmwh/react-refresh-webpack-plugin` . You can see it being used if you check out the source code at https://github.com/esetnik/customize-cra-react-refresh/blob/master/index.js#L2

**Comment by mnemanja** [comment]
Thanks, @esetnik.
